export class WeatherClient extends Signals.EventEmitter {
    _loading: boolean;
    _locationValid: boolean;
    _lastUpdate: any;
    _autoLocationRequested: boolean;
    _mostRecentLocation: any;
    _gclueService: any;
    _gclueStarted: boolean;
    _gclueStarting: boolean;
    _gclueLocationChangedId: number;
    _needsAuth: boolean;
    _weatherAuthorized: boolean;
    _permStore: any;
    _locationSettings: any;
    _world: any;
    _weatherInfo: any;
    _weatherApp: any;
    _weatherProxy: any;
    _settings: any;
    _appSystem: any;
    get available(): boolean;
    get loading(): boolean;
    get hasLocation(): boolean;
    get info(): any;
    activateApp(): void;
    update(): void;
    get _useAutoLocation(): boolean;
    _createWeatherProxy(): Promise<void>;
    _onWeatherPropertiesChanged(): void;
    _onInstalledChanged(): void;
    _loadInfo(): void;
    _locationsEqual(loc1: any, loc2: any): any;
    _setLocation(location: any): void;
    _updateLocationMonitoring(): void;
    _startGClueService(): Promise<void>;
    _onGClueLocationChanged(): void;
    _onAutomaticLocationChanged(): void;
    _updateAutoLocation(): void;
    _onLocationsChanged(): void;
    _onPermStoreChanged(proxy: any, sender: any, params: any): void;
}
import * as Signals from './signals.js';
